name: Test B Stepenv
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Echo with env
        env:
          CI: "true"
        run: |
          echo "hello from test B"
